account = "x0"
bind_pay = "x1"
lawsuit = "x2"
punish = "x3"
shop = "x4"
job_apply = "x5"
daily_cost = "x6"
work = "x7"
expense = "x8"
revenue = "x9"
salary = "x10"
invest = "x11"
invest_stock = "x12"
invest_fund = "x13"
invest_future = "x14"
insur = "x15"
insur_person = "x16"
insur_property = "x17"
insur_endowment = "x18"
insur_loan = "x19"
insur_apply = "x20"
insur_surrender = "x21"
insur_claim = "x22"
credit = "x23"
credit_apply = "x24"
credit_due = "x25"
credit_overdue = "x26"
provident = "x27"
provident_deposit = "x28"
provident_withdraw = "x29"
tele = "x30"
tele_owe = "x31"
tele_pay = "x32"
tele_business = "x33"
market_e_business = "x34"
market_invest = "x35"
market_insur = "x36"
market_credit_card = "x37"
market_loan = "x38"
market_edu = "x39"
market_gamble = "x40"
market_beauty = "x41"
market_estate = "x42"
market_decoration = "x43"
travel = "x44"
go = "x45"
stay = "x46"
epidemic = "x47"
